apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-cicd-deployment
spec:
  selector:
    matchLabels:
      app: aspnetcore-cicd-pod
  template:
    metadata:
      labels:
        app: aspnetcore-cicd-pod
    spec:
      containers:
      - name: aspnetcore-cicd-container
        image: annamalai2k11.azurecr.io/aspnetcore-cicd:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
